spring.application.name=marcoWebProy
server.port= 8086

#spring.datasource.url=jdbc:mysql://localhost:3306/SistemaReservas
#spring.datasource.username=root
#spring.datasource.password=admin

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#cambiar a el never a always cuando ya tengamos la base de datos
#spring.sql.init.mode=never
