spring.application.name=marcoWebProy
server.port= 8086

#spring.datasource.url=jdbc:h2:mem:sistema_reservas;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=root
#spring.datasource.password=admin

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#cambiar a el never a always cuando ya tengamos la base de datos
#spring.sql.init.mode=never
